name: Fetch Crypto Data

on:
  schedule:
    - cron: "*/10 * * * *"  # runs every 10 mins
  workflow_dispatch:       # lets you run manually too

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          SUPA_URL: ${{ secrets.SUPA_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python fetch_crypto.py
